name = "SDNOpt"
uuid = "41a8bc7a-cf88-41fe-9f96-db2474314a83"
version = "1.0.0-DEV"
authors = ["karlfroldan <karlfroldan@proton.me> and contributors"]

[deps]
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[compat]
CPLEX = "1.1.1"
GraphRecipes = "0.5.15"
Graphs = "1.13.3"
HiGHS = "1.20.1"
IJulia = "1.33.0"
JuMP = "1.29.3"
LinearAlgebra = "1.12.0"
MetaGraphsNext = "0.7.5"
PGFPlotsX = "1.6.2"
Plots = "1.41.4"
Printf = "1.11.0"
Random = "1.11.0"
SCIP = "0.12.8"
SimpleWeightedGraphs = "1.5.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
